services:
    Payourself2\Bundle\MonobankBundle\Client\GeneralClient:
        public: false
        arguments:
            - '@payourself2_monobank.action_sender'

    payourself2_monobank.general_client: '@Payourself2\Bundle\MonobankBundle\Client\GeneralClient'
        public: true

    Payourself2\Bundle\MonobankBundle\Client\PersonalClient:
        public: false
        arguments:
            - '@payourself2_monobank.action_sender'
            - '@payourself2_monobank.general_client'
            - '%payourself2_monobank.personal_key%'

    payourself2_monobank.personal_client: '@Payourself2\Bundle\MonobankBundle\Client\PersonalClient'
        public: true

    Payourself2\Bundle\MonobankBundle\Client\CorporateClient:
        public: false
        arguments:
            - '@payourself2_monobank.action_sender'
            - '@payourself2_monobank.action_signer'
            - '@payourself2_monobank.general_client'

    payourself2_monobank.corporate_client: '@Payourself2\Bundle\MonobankBundle\Client\CorporateClient'
        public: true


    Payourself2\Bundle\MonobankBundle\Action\ResponseDeserializer:
        public: false

    payourself2_monobank.action_response_deserializer: '@Payourself2\Bundle\MonobankBundle\Action\ResponseDeserializer'
        public: true


    Payourself2\Bundle\MonobankBundle\Action\Sender:
        public: false
        arguments:
            - '@payourself2_monobank.action_response_deserializer'
            - '@payourself2_monobank.action_status_code_checker'
            - '%payourself2_monobank.api_base_path%'

    payourself2_monobank.action_sender: '@Payourself2\Bundle\MonobankBundle\Action\Sender'
        public: true


    Payourself2\Bundle\MonobankBundle\Action\Signer:
        public: false
        arguments:
            - "%payourself2_monobank.pub_key%"
            - "%payourself2_monobank.priv_key%"

    payourself2_monobank.action_signer: '@Payourself2\Bundle\MonobankBundle\Action\Signer'
        public: true


    Payourself2\Bundle\MonobankBundle\Action\StatusCodeChecker:
        public: false

    payourself2_monobank.action_status_code_checker: '@Payourself2\Bundle\MonobankBundle\Action\StatusCodeChecker'
        public: true
