services:
    payourself2_monobank.general_client:
        class: Payourself2\Bundle\MonobankBundle\Client\GeneralClient
        public: true
        arguments:
            - '@payourself2_monobank.action_sender'

    payourself2_monobank.personal_client:
        class: Payourself2\Bundle\MonobankBundle\Client\PersonalClient
        public: true
        arguments:
            - '@payourself2_monobank.action_sender'
            - '@payourself2_monobank.general_client'
            - '%payourself2_monobank.personal_key%'

    payourself2_monobank.corporate_client:
        class: Payourself2\Bundle\MonobankBundle\Client\CorporateClient
        public: true
        arguments:
            - '@payourself2_monobank.action_sender'
            - '@payourself2_monobank.action_signer'
            - '@payourself2_monobank.general_client'

    payourself2_monobank.send_request_adapter:
        class: Payourself2\Bundle\MonobankBundle\Adapter\NullAdapter
        public: true

    payourself2_monobank.action_response_deserializer:
        class: Payourself2\Bundle\MonobankBundle\Action\ResponseDeserializer
        public: false

    payourself2_monobank.action_sender:
        class: Payourself2\Bundle\MonobankBundle\Action\Sender
        public: false
        arguments:
            - '@payourself2_monobank.send_request_adapter'
            - '@payourself2_monobank.action_response_deserializer'
            - '@payourself2_monobank.action_status_code_checker'
            - '%payourself2_monobank.api_base_path%'

    payourself2_monobank.action_signer:
        class: Payourself2\Bundle\MonobankBundle\Action\Signer
        public: false
        arguments:
            - "%payourself2_monobank.pub_key%"
            - "%payourself2_monobank.priv_key%"

    payourself2_monobank.action_status_code_checker:
        class: Payourself2\Bundle\MonobankBundle\Action\StatusCodeChecker
        public: false
