# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    monobank_api_base_path: 'https://api.monobank.ua'
    monobank_pub_key: '%env(MONOBANK_PUB_KEY)%'
    monobank_priv_key: '%env(MONOBANK_PRIV_KEY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $monobankApiBasePath: "%monobank_api_base_path%"
            string $monobankApiPublicKey: "%monobank_pub_key%"
            string $monobankApiPrivateKey: "%monobank_priv_key%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Payourself2\Bundle\MonobankBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Config/'
            - '../src/Models/'
            - '../src/Kernel.php'


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Payourself2\Bundle\MonobankBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
